# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='defualt.png', upload_to=b''),
        ),
    ]
