# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.CharField(max_length=100)),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
